Description: >
  RDS instance for the database

Parameters:
  InstanceType:
    Type: String
    Default: db.t3.micro
    AllowedValues:
      - db.t3.micro
      - db.t3.small
      - db.t3.medium
    Description: "The instance type for the RDS instance"

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for the RDS instance
      SubnetIds:
      - !ImportValue Booklogr-PrivateSubnet1
      - !ImportValue Booklogr-PrivateSubnet2

  RDSDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: booklogr-db
      AllocatedStorage: 20
      DBInstanceClass: !Ref InstanceType
      Engine: postgres
      MasterUsername: postgres
      MasterUserPassword: password
      DBName: booklogr
      PreferredBackupWindow: 09:03-09:33
      BackupRetentionPeriod: 7
      PreferredMaintenanceWindow: sat:06:10-sat:06:40
      MultiAZ: false
      EngineVersion: "18.3"
      AutoMinorVersionUpgrade: true
      LicenseModel: "postgresql-license"
      PubliclyAccessible: false
      StorageType: "gp3"
      Port: 5432
      StorageEncrypted: true
      CopyTagsToSnapshot: true
      MonitoringInterval: 0
      EnableIAMDatabaseAuthentication: false
      EnablePerformanceInsights: false
      DeletionProtection: false
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups: 
      - !ImportValue Booklogr-DatabaseSG
      MaxAllocatedStorage: 40
      DBParameterGroupName: "default.postgres18"
      OptionGroupName: "default:postgres-18"
      CACertificateIdentifier: "rds-ca-rsa2048-g1"
      SkipFinalSnapshot: true
      DeleteAutomatedBackups: true
    
Outputs:
  DBEndpoint:
    Description: "Endpoint of the RDS instance"
    Value: !GetAtt RDSDBInstance.Endpoint.Address
    Export:
      Name: Booklogr-DBEndpoint
